### ISSUE TITLE
First pass at crawling one Spektrix customer

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-spektrix#1]
Run a first test using one of their Canadian clients (8 hrs)
Decide how to represent the data in Artsdata: as an Event, as an Offer or both? parts: mapping the data , OntoRefine configuration to convert the json data to rdf, creating a repository and workflow, testing (16 hr)

**Comment by dev-aravind** [comment]
@saumier The data is up in artsdata right now, but the UI seems a bit off. Can you check [this](https://artsdata-nebula-d1ec887e2637.herokuapp.com/en/entity?uri=http%3A%2F%2Fwww.spektrix.com%2F175002AGKKJLCPBHQPHBGVHBDMNGBSBND) and let me know?

**Comment by saumier** [comment]
@dev-aravind Great progress. For the UI issue, please strip out all the <div xxx> </div> in the descriptions.  Then we can consider this first pass completed.

**Comment by dev-aravind** [comment]
@saumier  All these issues are resolved as of now, please review this and let me know if you need any other changes.

**Comment by saumier** [comment]
Great
